config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources 'comics'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :publisher, presence: true
  validates :year_published, presence: true, numericality: true
  validates :condition, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  def index
    @comics = Comic.all
  end

  def show
    @comic = Comic.find(params[:id])
  end

  def new
    @comic = Comic.new
  end

  def create
    @comic = Comic.new(comics_params)
    if @comic.save
      redirect_to @comic, notice: "Yay, you saved it!!"
    else
      render :new
    end
  end

  private
  def comics_params
    params.require(:comic).permit(
      :title,
      :illustrator,
      :publisher,
      :year_published,
      :ASIN,
      :condition
    )
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comics/_form.html.erb
<h3>Add a New Comic</h3>
<%= form_for @comic do  |f| %>
  <% if @comic.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@comic.errors.count, "error") %>
          prohibited this comic from being saved:
      </h2>

      <ul>
        <% @comic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :illustrator %><br>
    <%= f.text_field :illustrator %>
  </p>

  <p>
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </p>

  <p>
    <%= f.label :year_published, "Year Published"%><br>
    <%= f.text_field :year_published %>
  </p>

  <p>
    <%= f.label :ASIN, "ASIN" %><br>
    <%= f.text_field :ASIN %>
  </p>

  <p>
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </p>

  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/comics/index.html.erb
<h3>Comics</h3>
<div class="index">

<% @comics.each do |comic| %>
  <%= link_to comic.title, comic_path(comic) %><br>
<% end %>
</div>

app/views/comics/new.html.erb
<%= render 'form' %>

app/views/comics/show.html.erb
<h3>Title: <%= @comic.title %></h3>
<h5>Publisher: <%= @comic.publisher %></h5>
<h5>Illustrator: <%= @comic.illustrator %></h5>
<h5>Year Published: <%= @comic.year_published %></h5>
<h5>Condition: <%= @comic.condition %></h5>
<h5>ASIN: <%= @comic.ASIN %></h5>

<h3>Leave a Review</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reviewsite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <ul id="mainPage">
    <h2>
      <li><%= link_to "Add New Comic", new_comic_path %><br></li>
      <li><%= link_to "All Comics",  comics_path %></li>
      <li><%= link_to "Home", root_path %></li>
    </h2>
  </ul>

  <body>
    <% if flash.any? %>
      <%= flash[:notice] %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<table>
  <thead>
    <th><h1>Comic World</h1></th>
  </thead>

  <tbody>
    <tr>
      <td>Welcome to Comic World</td>
    </tr>

    <tr>
      <td>Add a New Comic or Graphic Novel</td>
    </tr>
    <tr>

      <td>Leave a Review for an existing Item!!!</td>
    </tr>
  </tbody>
</table>